// <auto-generated />
namespace GizmoDALV2.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update16));
        
        string IMigrationMetadata.Id
        {
            get { return "202208171348149_Update16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
