# Values are loaded from .env file in the same directory
# docker-compose -p gizmo-dal up -d
# docker-compose -p gizmo-dal down -v

services:
  #Server=localhost,1433;Database=Gizmo;User Id=sa;Password=$DB_PASSWORD;TrustServerCertificate=True;
  mssql:
    container_name: gizmo-dal-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - DB_NAME=Gizmo
      - BACKUP_PATH=/usr/backups
      - BACKUP_FILE=Gizmo_mssql.bak
    ports:
      - 1433:1433
    volumes:
      - mssql-volume:/var/opt/mssql
      - ${WINDOWS_BACKUP_PATH}:/usr/backups
    #   - ./init-db-scripts/init-mssql.sh:/usr/local/bin/init-mssql.sh
    # entrypoint: ["/usr/local/bin/init-mssql.sh"]
    networks:
      - gizmo-dal-network

  #Host=localhost;Port=5432;Database=Gizmo;Username=gizmo;Password=$DB_PASSWORD;
  postgres:
    container_name: gizmo-dal-postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=gizmo
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_NAME=Gizmo
      - BACKUP_PATH=/usr/backups
      - BACKUP_FILE=Gizmo_pgsql.dump
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ${WINDOWS_BACKUP_PATH}:/usr/backups
      # - ./init-db-scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    networks:
      - gizmo-dal-network

  adminer:
    container_name: gizmo-dal-adminer
    image: adminer
    ports:
      - 8082:8080
    networks:
      - gizmo-dal-network
  
networks:
  gizmo-dal-network:
    driver: bridge

volumes:
  mssql-volume:
  postgres-volume: