# Values are loaded from .env file in the same directory
# docker-compose -p gizmo-dal up -d
# docker-compose -p gizmo-dal down -v

services:
  #Server=localhost,1433;Database=$MSSQL_DB_NAME;User Id=sa;Password=$MSSQL_DB_PASSWORD;TrustServerCertificate=True;
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_SA_PASSWORD=${MSSQL_DB_PASSWORD}
      - DB_NAME=${MSSQL_DB_NAME}
      - DB_PASSWORD=${MSSQL_DB_PASSWORD}
      - BACKUP_PATH=${MSSQL_BACKUP_PATH}
      - BACKUP_FILE=${MSSQL_BACKUP_FILE}
    ports:
      - 1433:1433
    volumes:
      - mssql_volume:/var/opt/mssql
      - ${BACKUP_PATH}:${MSSQL_BACKUP_PATH}
      - ./init-db-scripts/init-mssql.sh:/usr/local/bin/init-mssql.sh
    entrypoint: ["/usr/local/bin/init-mssql.sh"]
    networks:
      - gizmo-database-network

  #Host=localhost;Port=5432;Database=$POSTGRES_DB_NAME;Username=$POSTGRES_USER;Password=$POSTGRES_DB_PASSWORD;
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - DB_NAME=${POSTGRES_DB_NAME}
      - BACKUP_PATH=${POSTGRES_BACKUP_PATH}
      - BACKUP_FILE=${POSTGRES_BACKUP_FILE}
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ${BACKUP_PATH}:${POSTGRES_BACKUP_PATH}
      - ./init-db-scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    networks:
      - gizmo-database-network

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8082:8080
    networks:
      - gizmo-database-network

networks:
  gizmo-database-network:
    driver: bridge

volumes:
  mssql_volume:
  postgres_volume:
  pgadmin_volume:
