// <auto-generated />
namespace GizmoDALV2.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update6));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091724358_Update6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
